version: '3'

services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - SERVICES=s3,sqs,lambda
      - DEFAULT_REGION=ap-northeast-1
      - DATA_DIR=/tmp/localstack/data
      - HOSTNAME_EXTERNAL=localstack
    volumes:
      - ./docker-entrypoint-initaws.d:/docker-entrypoint-initaws.d
      - ./volumes/localstack:/tmp/localstack # ローカルディレクトリをデータ保存ディレクトリへマウント
    ports:
      - 4566:4566 # サービスへのアクセスポートは4566
  sqs-insights:
    image: sqs-insight:latest
    volumes:
      - ./mounts/sqs-insight/config:/app/config
    ports:
      - 13000:3000 # サービスへのアクセスポートは4566
