version: '3'

services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - SERVICES=s3,sqs,lambda
      - DEFAULT_REGION=ap-northeast-1
      - DATA_DIR=/tmp/localstack/data
      - HOSTNAME_EXTERNAL=localstack
    volumes:
      - ./docker-entrypoint-initaws.d:/docker-entrypoint-initaws.d
    ports:
      - 4566:4566
